/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface AssetValueResponse {
  assetId?: number;
  assetName?: string;
  purchasePrice?: number;
  currentValue?: number;
  totalDepreciation?: number;
  depreciationRate?: number;
  salvageValue?: number;
  purchaseDate?: string;
  daysOwned?: number;
  yearsOwned?: number;
  valueAsOfDate?: string;
}
