/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface AssetResponse {
  id?: number;
  assetRef?: number;
  companyId?: number;
  name?: string;
  description?: string;
  serialNumber?: string;
  assetTag?: string;
  purchasePrice?: number;
  purchaseDate?: string;
  depreciationRate?: number;
  salvageValue?: number;
  available?: boolean;
  archived?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
