/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface AssetCreateRequest {
  /**
   * @minLength 2
   * @maxLength 150
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  serialNumber?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  assetTag?: string;
  /** @minimum 0.01 */
  purchasePrice: number;
  purchaseDate: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  depreciationRate: number;
  salvageValue?: number;
}
