/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface AssetAssignmentResponse {
  assignmentId?: number;
  assetId?: number;
  jobId?: number;
  assignedWorkerId?: number;
  assetName?: string;
  description?: string;
  serialNumber?: string;
  assetTag?: string;
  notes?: string;
  assignedAt?: string;
  returnedAt?: string;
  durationDays?: number;
  status?: string;
}
