/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface ClientResponse {
  id?: number;
  clientRef?: number;
  name?: string;
  email?: string;
  telephone?: string;
  mobile?: string;
  address?: string;
  archived?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
