/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface CompanyAddressResponse {
  addressLine1?: string;
  addressLine2?: string;
  addressLine3?: string;
  town?: string;
  country?: string;
  postcode?: string;
}
