/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { CompanyAddressRequest } from './companyAddressRequest';
import type { CompanyBankDetailsRequest } from './companyBankDetailsRequest';
import type { CompanyProfileUpdateRequestCurrency } from './companyProfileUpdateRequestCurrency';

export interface CompanyProfileUpdateRequest {
  /**
   * @minLength 2
   * @maxLength 150
   */
  name: string;
  address?: CompanyAddressRequest;
  /**
   * @minLength 0
   * @maxLength 20
   */
  telephone?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  mobile?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  fax?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  contactEmail?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  contactNumber?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  vatNumber?: string;
  bankDetails?: CompanyBankDetailsRequest;
  currency?: CompanyProfileUpdateRequestCurrency;
}
