/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface CompanyAddressRequest {
  /**
   * @minLength 0
   * @maxLength 255
   */
  addressLine1?: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  addressLine2?: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  addressLine3?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  town?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  country?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  postcode?: string;
}
