/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface CompanyBankDetailsRequest {
  /**
   * @minLength 0
   * @maxLength 100
   */
  bankName?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  accountName?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  accountNo?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  sortCode?: string;
}
