/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export type CompanyProfileResponseCurrency = typeof CompanyProfileResponseCurrency[keyof typeof CompanyProfileResponseCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyProfileResponseCurrency = {
  GBP: 'GBP',
  EUR: 'EUR',
  USD: 'USD',
  CAD: 'CAD',
  AUD: 'AUD',
  NZD: 'NZD',
  CHF: 'CHF',
  JPY: 'JPY',
  SEK: 'SEK',
  NOK: 'NOK',
  DKK: 'DKK',
  SGD: 'SGD',
  AED: 'AED',
  SAR: 'SAR',
  INR: 'INR',
  ZAR: 'ZAR',
} as const;
