/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { CompanyAddressResponse } from './companyAddressResponse';
import type { CompanyBankDetailsResponse } from './companyBankDetailsResponse';
import type { CompanyProfileResponseCurrency } from './companyProfileResponseCurrency';

export interface CompanyProfileResponse {
  id?: number;
  name?: string;
  address?: CompanyAddressResponse;
  telephone?: string;
  mobile?: string;
  fax?: string;
  email?: string;
  contactEmail?: string;
  contactNumber?: string;
  vatNumber?: string;
  bankDetails?: CompanyBankDetailsResponse;
  currency?: CompanyProfileResponseCurrency;
  archived?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
