/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { CustomerAddressDto } from './customerAddressDto';

export interface CustomerResponse {
  id?: number;
  customerRef?: number;
  name?: string;
  email?: string;
  telephone?: string;
  mobile?: string;
  address?: CustomerAddressDto;
  archived?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
