/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { CustomerAddressDto } from './customerAddressDto';

export interface CustomerCreateRequest {
  /**
   * @minLength 2
   * @maxLength 150
   */
  name: string;
  email?: string;
  telephone?: string;
  mobile?: string;
  address?: CustomerAddressDto;
}
