/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export type FieldValueResponseType = typeof FieldValueResponseType[keyof typeof FieldValueResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FieldValueResponseType = {
  TEXT: 'TEXT',
  NUMBER: 'NUMBER',
  DATE: 'DATE',
  BOOLEAN: 'BOOLEAN',
  DROPDOWN: 'DROPDOWN',
  JSON: 'JSON',
  REFERENCE: 'REFERENCE',
} as const;
