/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { LineItemResponse } from './lineItemResponse';

export interface InvoiceResponse {
  id?: number;
  estimateId?: number;
  companyId?: number;
  invoiceNumber?: string;
  dueDate?: string;
  reference?: string;
  presignedUrl?: string;
  lineItems?: LineItemResponse[];
  totalNet?: number;
  totalVat?: number;
  grandTotal?: number;
  createdAt?: string;
  updatedAt?: string;
}
