/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface InvoiceCreateRequest {
  /** @minItems 1 */
  lineItemIds: number[];
  dueDate?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  reference?: string;
}
