/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { JobCreateRequestStatus } from './jobCreateRequestStatus';
import type { JobCreateRequestFieldValues } from './jobCreateRequestFieldValues';
import type { AddressRequest } from './addressRequest';

export interface JobCreateRequest {
  templateId: number;
  clientId?: number;
  customerId: number;
  assignedWorkerId?: number;
  workflowId?: number;
  status?: JobCreateRequestStatus;
  fieldValues?: JobCreateRequestFieldValues;
  assetIds?: number[];
  address?: AddressRequest;
}
