/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { JobResponseStatus } from './jobResponseStatus';
import type { JobResponseFieldValues } from './jobResponseFieldValues';
import type { AddressResponse } from './addressResponse';

export interface JobResponse {
  id?: number;
  jobRef?: number;
  companyId?: number;
  templateId?: number;
  clientId?: number;
  customerId?: number;
  assignedWorkerId?: number;
  workflowId?: number;
  status?: JobResponseStatus;
  archived?: boolean;
  createdAt?: string;
  updatedAt?: string;
  fieldValues?: JobResponseFieldValues;
  assetIds?: number[];
  address?: AddressResponse;
}
