/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { JobTemplateFieldCreateRequestJobFieldType } from './jobTemplateFieldCreateRequestJobFieldType';

export interface JobTemplateFieldCreateRequest {
  templateId: number;
  /**
   * @minLength 0
   * @maxLength 150
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 150
   */
  label: string;
  jobFieldType: JobTemplateFieldCreateRequestJobFieldType;
  required?: boolean;
  options?: string;
  orderIndex?: number;
}
