/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { JobTemplateFieldResponseJobFieldType } from './jobTemplateFieldResponseJobFieldType';

export interface JobTemplateFieldResponse {
  id?: number;
  templateId?: number;
  name?: string;
  label?: string;
  jobFieldType?: JobTemplateFieldResponseJobFieldType;
  required?: boolean;
  options?: string;
  orderIndex?: number;
}
