/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export type JobUpdateRequestStatus = typeof JobUpdateRequestStatus[keyof typeof JobUpdateRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobUpdateRequestStatus = {
  NEW: 'NEW',
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
