/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { JobUpdateRequestStatus } from './jobUpdateRequestStatus';
import type { JobUpdateRequestFieldValues } from './jobUpdateRequestFieldValues';
import type { AddressRequest } from './addressRequest';

export interface JobUpdateRequest {
  clientId?: number;
  customerId?: number;
  assignedWorkerId?: number;
  workflowId?: number;
  status?: JobUpdateRequestStatus;
  archived?: boolean;
  fieldValues?: JobUpdateRequestFieldValues;
  assetIds?: number[];
  address?: AddressRequest;
}
