/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export type JobWorkflowStepCreateRequestStatus = typeof JobWorkflowStepCreateRequestStatus[keyof typeof JobWorkflowStepCreateRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobWorkflowStepCreateRequestStatus = {
  INITIATED: 'INITIATED',
  NOT_STARTED: 'NOT_STARTED',
  PENDING: 'PENDING',
  ONGOING: 'ONGOING',
  STARTED: 'STARTED',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
} as const;
