/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { JobWorkflowStepCreateRequestStatus } from './jobWorkflowStepCreateRequestStatus';

export interface JobWorkflowStepCreateRequest {
  name?: string;
  description?: string;
  orderIndex?: number;
  status?: JobWorkflowStepCreateRequestStatus;
  assignedWorkerIds?: number[];
}
