/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { LineItemResponseCoreOrSub } from './lineItemResponseCoreOrSub';

export interface LineItemResponse {
  id?: number;
  companyId?: number;
  productCode?: string;
  productDescription?: string;
  additionalDetails?: string;
  unitPrice?: number;
  coreOrSub?: LineItemResponseCoreOrSub;
  quantity?: number;
  vatRate?: number;
  netAmount?: number;
  vatAmount?: number;
  totalAmount?: number;
  invoiced?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
