/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { LineItemCreateRequestCoreOrSub } from './lineItemCreateRequestCoreOrSub';

export interface LineItemCreateRequest {
  /** @minLength 1 */
  productCode: string;
  /** @minLength 1 */
  productDescription: string;
  additionalDetails?: string;
  /** @minimum 0 */
  unitPrice: number;
  coreOrSub: LineItemCreateRequestCoreOrSub;
  /** @minimum 0 */
  quantity: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  vatRate: number;
}
