/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { AssetResponse } from './assetResponse';
import type { SortObject } from './sortObject';
import type { PageableObject } from './pageableObject';

export interface PageAssetResponse {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: AssetResponse[];
  number?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  numberOfElements?: number;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
