/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface ResetPasswordRequest {
  /** @minLength 1 */
  email: string;
  /**
   * @minLength 1
   * @pattern ^\d{6}$
   */
  code: string;
  /**
   * @minLength 8
   * @maxLength 2147483647
   */
  newPassword: string;
}
