/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export type SignupRequestRole = typeof SignupRequestRole[keyof typeof SignupRequestRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignupRequestRole = {
  WORKER: 'WORKER',
  COMPANY: 'COMPANY',
  ADMIN: 'ADMIN',
} as const;
