/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { StepTimelineItemResponseDiscussionType } from './stepTimelineItemResponseDiscussionType';

export interface StepTimelineItemResponse {
  id?: number;
  itemType?: string;
  content?: string;
  fileUrl?: string;
  discussionType?: StepTimelineItemResponseDiscussionType;
  description?: string;
  actorId?: number;
  createdAt?: string;
}
