/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { StepCommentCreateRequestType } from './stepCommentCreateRequestType';

export interface StepCommentCreateRequest {
  /** @minLength 1 */
  content: string;
  type: StepCommentCreateRequestType;
}
