/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { StepAttachmentResponseType } from './stepAttachmentResponseType';

export interface StepAttachmentResponse {
  id?: number;
  fileName?: string;
  fileType?: string;
  fileUrl?: string;
  description?: string;
  type?: StepAttachmentResponseType;
  uploadedBy?: number;
  createdAt?: string;
}
