/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface WorkerResponse {
  id?: number;
  workerRef?: number;
  name?: string;
  initials?: string;
  telephone?: string;
  mobile?: string;
  email?: string;
  username?: string;
  loginLocked?: boolean;
  archived?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
