/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface WorkerCreateRequest {
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 10
   */
  initials?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  telephone?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  mobile?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  email?: string;
  /**
   * @minLength 3
   * @maxLength 20
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 2147483647
   */
  password: string;
}
