/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export type WorkerJobWorkflowUploadAttachmentType = typeof WorkerJobWorkflowUploadAttachmentType[keyof typeof WorkerJobWorkflowUploadAttachmentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkerJobWorkflowUploadAttachmentType = {
  GENERAL: 'GENERAL',
  ADDITIONAL: 'ADDITIONAL',
  COMPLAINT: 'COMPLAINT',
  INTERNAL_NOTE: 'INTERNAL_NOTE',
  APPROVAL: 'APPROVAL',
  REJECTION: 'REJECTION',
} as const;
