/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export type WorkerInvitationCheckResponseStatus = typeof WorkerInvitationCheckResponseStatus[keyof typeof WorkerInvitationCheckResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkerInvitationCheckResponseStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  EXPIRED: 'EXPIRED',
} as const;
