/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */

export interface WorkerUpdateRequest {
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 10
   */
  initials?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  telephone?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  mobile?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  email: string;
}
