/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { WorkflowStepBulkRequest } from './workflowStepBulkRequest';

export interface WorkflowBulkUpdateRequest {
  name?: string;
  description?: string;
  steps?: WorkflowStepBulkRequest[];
}
