/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { WorkerInvitationStatusResponseStatus } from './workerInvitationStatusResponseStatus';

export interface WorkerInvitationStatusResponse {
  invitationId?: number;
  email?: string;
  status?: WorkerInvitationStatusResponseStatus;
  createdAt?: string;
  expiresAt?: string;
  usedAt?: string;
}
