/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Work Flow API
 * This is the REST API for Work Flow
 * OpenAPI spec version: V0.0.1
 */
import type { JobWorkflowStepResponse } from './jobWorkflowStepResponse';
import type { CustomerResponse } from './customerResponse';
import type { AssetAssignmentResponse } from './assetAssignmentResponse';
import type { AddressResponse } from './addressResponse';

export interface WorkerAssignedStepResponse {
  step?: JobWorkflowStepResponse;
  jobId?: number;
  jobRef?: number;
  customer?: CustomerResponse;
  assignedAssets?: AssetAssignmentResponse[];
  jobAddress?: AddressResponse;
}
